version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: maritime_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
  celery:
    build: .
    command: celery -A celery_worker.celery worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  postgres_data: